from __future__ import annotations

import ctypes
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from projectflow.cad import document_manager
from projectflow.cad.document_manager import ComApi, open_document_manager
from projectflow.cad.document_manager_registry import (
    class_factory_prog_ids,
    diagnose_document_manager,
    registered_dll_path,
)
from projectflow.exceptions import CadError, CadUnavailableError


class FakeCOMError(Exception):
    pass


class FakeComtypes:
    COMError = FakeCOMError


class FakeModule:
    """Interfaces generated by comtypes from the Document Manager type library."""

    class SwDMClassFactory:
        pass

    class ISwDMClassFactory:
        pass

    class ISwDMApplication:
        pass

    class ISwDMApplication4:
        pass

    class ISwDMDocument:
        pass

    class ISwDMDocument19:
        pass

    class ISwDMSearchOption:
        pass

    class ISwDMConfiguration:
        pass

    class ISwDMConfiguration14:
        pass

    class ISwDMComponent:
        pass

    class ISwDMComponent9:
        pass


class Interfaced:
    """Answer QueryInterface only for the interfaces listed in ``supported``."""

    supported: tuple[type, ...] = ()

    def __init__(self) -> None:
        self.queried: list[type] = []

    def QueryInterface(self, interface: type) -> Any:  # noqa: N802
        self.queried.append(interface)
        if interface not in self.supported:
            raise FakeCOMError(-2147467262, "No such interface supported")
        return self


class FakeSearch(Interfaced):
    supported = (FakeModule.ISwDMSearchOption,)
    SearchFilters = 0


class FakeDocument(Interfaced):
    supported = (FakeModule.ISwDMDocument19,)

    def __init__(self) -> None:
        super().__init__()
        self.properties = {"Projet": "20XX-XXXX"}
        self.references = ("C:/Modeles/20XX-XXXX-PRT-100.SLDPRT",)
        self.replaced: list[tuple[str, str]] = []
        self.save_result = 0
        self.closed = False

    def GetCustomPropertyNames(self) -> tuple[str, ...]:  # noqa: N802
        return tuple(self.properties)

    def GetCustomProperty(self, name: str) -> tuple[int, str]:  # noqa: N802
        return 30, self.properties[name]

    def SetCustomProperty(self, name: str, value: str) -> bool:  # noqa: N802
        self.properties[name] = value
        return True

    def AddCustomProperty(self, name: str, value_type: int, value: str) -> bool:  # noqa: N802
        assert value_type == 30
        self.properties[name] = value
        return True

    def GetAllExternalReferences(self, search: FakeSearch) -> tuple[str, ...]:  # noqa: N802
        assert search.SearchFilters == 9
        return self.references

    def ReplaceReference(self, old: str, new: str) -> None:  # noqa: N802
        self.replaced.append((old, new))

    def Save(self) -> int:  # noqa: N802
        return self.save_result

    def CloseDoc(self) -> None:  # noqa: N802
        self.closed = True


class FakeApplication(Interfaced):
    supported = (FakeModule.ISwDMApplication4,)

    def __init__(self, document: FakeDocument | None, error: int = 0) -> None:
        super().__init__()
        self.document = document
        self.error = error
        self.opened: list[tuple[str, int, bool]] = []

    def GetDocument(  # noqa: N802
        self,
        path: str,
        document_type: int,
        read_only: bool,  # noqa: FBT001 - COM positional signature
    ) -> tuple[int, FakeDocument | None]:
        self.opened.append((path, document_type, read_only))
        return self.error, self.document

    def GetSearchOptionObject(self) -> FakeSearch:  # noqa: N802
        return FakeSearch()


class FakeFactory(Interfaced):
    def __init__(self, application: FakeApplication | None) -> None:
        super().__init__()
        self.application = application
        self.keys: list[str] = []

    def GetApplication(self, key: str) -> FakeApplication | None:  # noqa: N802
        self.keys.append(key)
        return self.application


class FakeClient:
    def __init__(self, factory: FakeFactory | None) -> None:
        self.factory = factory
        self.created: list[tuple[object, object]] = []

    def CreateObject(self, progid: object, *, interface: object) -> FakeFactory:  # noqa: N802
        self.created.append((progid, interface))
        if self.factory is None:
            raise FakeCOMError(-2147221164, "Classe non enregistree")
        return self.factory


class FakeRegistry:
    def __init__(
        self,
        values: dict[str, str] | None = None,
        values_32: dict[str, str] | None = None,
        keys: list[str] | None = None,
    ) -> None:
        self.values = values or {}
        self.values_32 = values_32 or {}
        self.keys = keys or []

    def default_value(self, path: str, *, wow64_32: bool = False) -> str | None:
        return (self.values_32 if wow64_32 else self.values).get(path)

    def subkeys(self, path: str = "") -> list[str]:
        assert path == ""
        return self.keys


def _install(monkeypatch: pytest.MonkeyPatch, factory: FakeFactory | None) -> FakeClient:
    client = FakeClient(factory)
    com = ComApi(FakeComtypes(), client, FakeModule)
    monkeypatch.setattr(document_manager, "_load_com_api", lambda: com)
    monkeypatch.setattr(document_manager, "default_registry", FakeRegistry)
    monkeypatch.setattr(
        "projectflow.cad.document_manager_registry.installed_dll_candidates",
        list,
    )
    return client


def test_document_manager_uses_typed_interfaces(monkeypatch: pytest.MonkeyPatch) -> None:
    document = FakeDocument()
    application = FakeApplication(document)
    factory = FakeFactory(application)
    client = _install(monkeypatch, factory)

    with (
        open_document_manager(" cle ") as manager,
        manager.open_document(Path("C:/Projet/2026-5233-ENS-100.SLDASM")) as opened,
    ):
        assert opened.custom_properties() == {"Projet": "20XX-XXXX"}
        opened.set_custom_property("Projet", "2026-5233")
        opened.set_custom_property("Client", "Client SA")
        assert opened.external_references() == ["C:/Modeles/20XX-XXXX-PRT-100.SLDPRT"]
        opened.replace_reference("C:/Modeles/a.SLDPRT", "C:/Projet/a.SLDPRT")
        opened.save()

    assert client.created == [(FakeModule.SwDMClassFactory, FakeModule.ISwDMClassFactory)]
    assert factory.keys == ["cle"]
    assert application.queried == [FakeModule.ISwDMApplication4]
    assert document.queried == [FakeModule.ISwDMDocument19]
    assert application.opened == [(str(Path("C:/Projet/2026-5233-ENS-100.SLDASM")), 2, False)]
    assert document.properties == {"Projet": "2026-5233", "Client": "Client SA"}
    assert document.replaced == [("C:/Modeles/a.SLDPRT", "C:/Projet/a.SLDPRT")]
    assert document.closed


def test_document_manager_invalid_license_is_unavailable(monkeypatch: pytest.MonkeyPatch) -> None:
    _install(monkeypatch, FakeFactory(FakeApplication(None, error=5)))

    with (
        pytest.raises(CadUnavailableError, match="licence"),
        open_document_manager("cle") as manager,
        manager.open_document(Path("a.SLDPRT"), read_only=True),
    ):
        pass


@pytest.mark.parametrize(
    ("factory", "message"),
    [
        (None, "introuvable : SwDocumentMgr.dll est introuvable.*0x80040154"),
        (FakeFactory(None), "refusee"),
    ],
)
def test_document_manager_absent_or_key_refused(
    monkeypatch: pytest.MonkeyPatch,
    factory: FakeFactory | None,
    message: str,
) -> None:
    _install(monkeypatch, factory)

    with pytest.raises(CadUnavailableError, match=message), open_document_manager("cle"):
        pass


def test_document_manager_reports_open_and_save_errors(monkeypatch: pytest.MonkeyPatch) -> None:
    document = FakeDocument()
    document.save_result = 1
    application: Any = FakeApplication(document)
    _install(monkeypatch, FakeFactory(application))

    with open_document_manager("cle") as manager:
        with (
            pytest.raises(CadError, match="Enregistrement"),
            manager.open_document(Path("a.SLDPRT")) as opened,
        ):
            opened.save()
        with pytest.raises(CadError, match="non gere"), manager.open_document(Path("a.dwg")):
            pass
        application.error = 3
        with (
            pytest.raises(CadError, match="non telecharge depuis OneDrive"),
            manager.open_document(Path("a.SLDPRT")),
        ):
            pass


def test_missing_license_key_is_unavailable() -> None:
    with pytest.raises(CadUnavailableError, match="non configuree"), open_document_manager(" "):
        pass


def test_registered_dll_and_versioned_prog_ids(tmp_path: Path) -> None:
    dll = tmp_path / "swdocumentmgr.dll"
    dll.write_bytes(b"")
    registry = FakeRegistry(
        values={
            "SwDocumentMgr.SwDMClassFactory.34\\CLSID": "{CLSID}",
            "CLSID\\{CLSID}\\InprocServer32": f'"{dll}"',
        },
        keys=[
            "SwDocumentMgr.SwDMClassFactory.33",
            "SwDocumentMgr.SwDMClassFactory.34",
            "Other.Class",
        ],
    )

    assert class_factory_prog_ids(registry) == [
        "SwDocumentMgr.SwDMClassFactory",
        "SwDocumentMgr.SwDMClassFactory.34",
        "SwDocumentMgr.SwDMClassFactory.33",
    ]
    assert registered_dll_path(registry) == dll
    assert registered_dll_path(FakeRegistry()) is None
    assert registered_dll_path(None) is None


def test_diagnose_dll_present_but_not_registered(tmp_path: Path) -> None:
    dll = tmp_path / "SwDocumentMgr.dll"
    dll.write_bytes(b"")

    reason = diagnose_document_manager(FakeRegistry(), dll_candidates=lambda: [dll])

    assert "n'est pas inscrit" in reason
    assert f'regsvr32 "{dll}"' in reason


def test_diagnose_registered_in_32_bits_only() -> None:
    registry = FakeRegistry(
        values={"SwDocumentMgr.SwDMClassFactory\\CLSID": "{CLSID}"},
        values_32={"CLSID\\{CLSID}\\InprocServer32": "C:/x86/SwDocumentMgr.dll"},
    )

    assert "32 bits seulement" in diagnose_document_manager(registry, dll_candidates=list)


def test_diagnose_registered_dll_missing(tmp_path: Path) -> None:
    missing = tmp_path / "absent" / "SwDocumentMgr.dll"
    registry = FakeRegistry(
        values={
            "SwDocumentMgr.SwDMClassFactory\\CLSID": "{CLSID}",
            "CLSID\\{CLSID}\\InprocServer32": f'"{missing}"',
        },
    )

    assert "DLL inscrite" in diagnose_document_manager(registry, dll_candidates=list)


def test_diagnose_without_registry() -> None:
    assert diagnose_document_manager(None) == "registre Windows inaccessible"


class FakeComponent(Interfaced):
    supported = (FakeModule.ISwDMComponent9,)

    def __init__(self, path: str) -> None:
        super().__init__()
        self.PathName = path


class FakeConfiguration(Interfaced):
    supported = (FakeModule.ISwDMConfiguration14,)

    def __init__(self, paths: list[str]) -> None:
        super().__init__()
        self.paths = paths

    def GetComponents(self) -> tuple[FakeComponent, ...]:  # noqa: N802
        return tuple(FakeComponent(path) for path in self.paths)


class FakeConfigurationManager:
    def __init__(self, configurations: dict[str, list[str]]) -> None:
        self.configurations = configurations

    def GetConfigurationNames(self) -> tuple[str, ...]:  # noqa: N802
        return tuple(self.configurations)

    def GetConfigurationByName(self, name: str) -> FakeConfiguration:  # noqa: N802
        return FakeConfiguration(self.configurations[name])


class AssemblyDocument(FakeDocument):
    def __init__(self) -> None:
        super().__init__()
        self.references = ()
        self.ConfigurationManager = FakeConfigurationManager(
            {
                "Defaut": ["C:/Modeles/20XX-XXXX-PRT-100.SLDPRT"],
                "Variante": [
                    "C:/Modeles/20XX-XXXX-PRT-100.SLDPRT",
                    "C:/Modeles/20XX-XXXX-PRT-200.SLDPRT",
                ],
            },
        )

    def GetAllExternalReferences4(self, search: FakeSearch) -> tuple[object, ...]:  # noqa: N802
        del search
        return ((False,), (False,), (0,), ("C:/Modeles/20XX-XXXX-ENV-100.SLDPRT",))


def test_document_manager_merges_listed_references_and_components(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _install(monkeypatch, FakeFactory(FakeApplication(AssemblyDocument())))

    with (
        open_document_manager("cle") as manager,
        manager.open_document(Path("C:/Projet/2026-5233-ENS-100.SLDASM")) as opened,
    ):
        references = opened.external_references()

    assert references == [
        "C:/Modeles/20XX-XXXX-ENV-100.SLDPRT",
        "C:/Modeles/20XX-XXXX-PRT-100.SLDPRT",
        "C:/Modeles/20XX-XXXX-PRT-200.SLDPRT",
    ]


class FailingListDocument(AssemblyDocument):
    """Document Manager versions whose newest method returns unsupported COM arrays."""

    def GetAllExternalReferences4(self, search: FakeSearch) -> tuple[object, ...]:  # noqa: N802
        del search
        raise KeyError(13)

    def GetAllExternalReferences(self, search: FakeSearch) -> tuple[str, ...]:  # noqa: N802
        del search
        return ("C:/Modeles/20XX-XXXX-ENV-100.SLDPRT",)


class FailingComponentsConfiguration(FakeConfiguration):
    def GetComponents(self) -> tuple[FakeComponent, ...]:  # noqa: N802
        raise KeyError(13)


def test_document_manager_reports_each_reference_source(monkeypatch: pytest.MonkeyPatch) -> None:
    document = FailingListDocument()
    _install(monkeypatch, FakeFactory(FakeApplication(document)))

    with (
        open_document_manager("cle") as manager,
        manager.open_document(Path("C:/Projet/2026-5233-ENS-100.SLDASM")) as opened,
    ):
        references = opened.external_references()
        report = opened.reference_report()

    assert references[0] == "C:/Modeles/20XX-XXXX-ENV-100.SLDPRT"
    assert len(references) == 3
    assert report == "liste : 1 ; composants : 3"


def test_document_manager_keeps_listed_references_when_components_fail(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    document = AssemblyDocument()
    document.ConfigurationManager.GetConfigurationByName = (  # type: ignore[method-assign]
        lambda _name: FailingComponentsConfiguration(["unused"])
    )
    _install(monkeypatch, FakeFactory(FakeApplication(document)))

    with (
        open_document_manager("cle") as manager,
        manager.open_document(Path("C:/Projet/2026-5233-ENS-100.SLDASM")) as opened,
    ):
        references = opened.external_references()
        report = opened.reference_report()

    assert references == ["C:/Modeles/20XX-XXXX-ENV-100.SLDPRT"]
    assert report == "liste : 1 ; composants : KeyError 13"


def test_parts_only_read_the_reference_list(monkeypatch: pytest.MonkeyPatch) -> None:
    document = FakeDocument()
    _install(monkeypatch, FakeFactory(FakeApplication(document)))

    with (
        open_document_manager("cle") as manager,
        manager.open_document(Path("C:/Projet/2026-5233-PRT-100.SLDPRT")) as opened,
    ):
        opened.external_references()
        assert opened.reference_report() == "liste : 1"


_VT_ARRAY_OF_VARIANTS = 0x2000 | 12
_VT_ARRAY_OF_UNKNOWN = 0x2000 | 13


def _target(reference: Any) -> Any:
    """Return the object a ctypes ``byref()`` argument points to."""
    return reference._obj  # noqa: SLF001 - ctypes stores the target there


class FakeVariant(ctypes.Structure):
    """VARIANT stand-in: ``index`` selects the COM object an element holds."""

    _fields_ = (("vt", ctypes.c_ushort), ("index", ctypes.c_int))
    objects: tuple[object, ...] = ()

    @property
    def _(self) -> SimpleNamespace:
        return SimpleNamespace(c_void_p=4096)

    @property
    def value(self) -> object:
        return self.objects[self.index]


class FakeOleAut32:
    def __init__(self, count: int, *, element_address: list[int] | None = None) -> None:
        self.count = count
        self.element_address = element_address
        self.cleared = 0

    def SafeArrayGetLBound(self, array: Any, dimension: int, out: Any) -> None:  # noqa: N802
        assert array.value == 4096
        assert dimension == 1
        _target(out).value = 0

    def SafeArrayGetUBound(self, array: Any, dimension: int, out: Any) -> None:  # noqa: N802
        del array, dimension
        _target(out).value = self.count - 1

    def SafeArrayGetElement(self, array: Any, position: Any, out: Any) -> None:  # noqa: N802
        del array
        index = _target(position).value
        if self.element_address is not None:
            _target(out).value = self.element_address[index]
            return
        _target(out).vt = 13
        _target(out).index = index

    def VariantClear(self, variant: Any) -> None:  # noqa: N802
        del variant
        self.cleared += 1


class RawConfiguration:
    def __init__(self, vartype: int) -> None:
        self.vartype = vartype

    def _ISwDMConfiguration2__com_GetComponents(self, out: Any) -> None:  # noqa: N802
        _target(out).vt = self.vartype

    def GetComponents(self) -> None:  # noqa: N802
        raise KeyError(13)


def test_object_array_decodes_variant_array_without_comtypes_conversion() -> None:
    components = (FakeComponent("C:/a.SLDPRT"), FakeComponent("C:/b.SLDPRT"))
    FakeVariant.objects = components
    oleaut32 = FakeOleAut32(2)
    com = ComApi(
        FakeComtypes(),
        FakeClient(None),
        FakeModule,
        automation=SimpleNamespace(VARIANT=FakeVariant),
        oleaut32=oleaut32,
    )

    items = com.object_array(RawConfiguration(_VT_ARRAY_OF_VARIANTS), "GetComponents")

    assert items == list(components)
    assert oleaut32.cleared == 3


def test_object_array_decodes_array_of_com_pointers() -> None:
    values = (ctypes.c_int * 2)(7, 9)
    addresses = [ctypes.addressof(values) + index * ctypes.sizeof(ctypes.c_int) for index in (0, 1)]
    oleaut32 = FakeOleAut32(2, element_address=addresses)
    comtypes = FakeComtypes()
    comtypes.IUnknown = ctypes.c_int  # type: ignore[attr-defined]
    com = ComApi(
        comtypes,
        FakeClient(None),
        FakeModule,
        automation=SimpleNamespace(VARIANT=FakeVariant),
        oleaut32=oleaut32,
    )

    items = com.object_array(RawConfiguration(_VT_ARRAY_OF_UNKNOWN), "GetComponents")

    assert [item.contents.value for item in items] == [7, 9]
    assert oleaut32.cleared == 1


def test_object_array_empty_variant_and_fallback_without_raw_method() -> None:
    oleaut32 = FakeOleAut32(0)
    com = ComApi(
        FakeComtypes(),
        FakeClient(None),
        FakeModule,
        automation=SimpleNamespace(VARIANT=FakeVariant),
        oleaut32=oleaut32,
    )

    assert com.object_array(RawConfiguration(0), "GetComponents") == []
    assert com.object_array(FakeConfiguration(["C:/a.SLDPRT"]), "GetComponents")[0].PathName == (
        "C:/a.SLDPRT"
    )
    with pytest.raises(CadError, match="tableau COM inattendu"):
        com.object_array(RawConfiguration(8), "GetComponents")


class TypedArrayConfiguration(FakeConfiguration):
    def _ISwDMConfiguration2__com_GetComponents(self, out: Any) -> None:  # noqa: N802
        del out
        raise ctypes.ArgumentError("argument 1: wrong type")


def test_object_array_falls_back_when_raw_method_is_not_a_variant() -> None:
    com = ComApi(
        FakeComtypes(),
        FakeClient(None),
        FakeModule,
        automation=SimpleNamespace(VARIANT=FakeVariant),
        oleaut32=FakeOleAut32(0),
    )

    items = com.object_array(TypedArrayConfiguration(["C:/a.SLDPRT"]), "GetComponents")

    assert [item.PathName for item in items] == ["C:/a.SLDPRT"]
